export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_SUCCESS = 'login_success'
export const LOGIN_FAIL = 'login_fail'
export const SIGN_OUT = 'signout'
// export const USER_LOGIN_SUCCESS = ''